name: at_robot

on: [pull_request]

jobs:
  at_robot:
  if contains(github.event.comment.body, '@cocos-robot run test cases')
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
      #with:
      #  path: engine    
    - name: run test cases
      run: |
         echo "call run test cases"
