name: automation-labels

on:
  pull_request:
    types: [opened]

jobs:
  automate-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check if organization member
        id: is_organization_member
        uses: jamessingleton/is-organization-member@1.0.0
        with:
          organization: OperationsYU
          username: ${{ github.event.pull_request.user.login }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: add_label
        if: steps.is_organization_member.outputs.result == true
        uses: andymckay/labeler@master
        with:
          add-labels: "contribution"
