name: 'Check Develop Environment'

on: 
  pull_request:
    types: [closed]

jobs:
  WinEnvironment:
    if: github.event.pull_request.merged == true
    runs-on: run-test-win01
    steps:
      - name: checkOut code
        uses: actions/checkout@v3
      - name: Check .update-cache.json
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "./workflow/.update-cache.json"
