name: Assign Generated PR2

on: pull_request_target


jobs:
  auto-assign-repo:
    #if: 
    #  (contains(github.event.pull_request.body, 'Automated PR to genbindings'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Locate and assign issue
        env:
          PR_NUMBER: ${{github.event.number}}
          # REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
          # REPO_TOKEN: ${{secrets.PR_TOKEN}}
          REPO_TOKEN: ${{secrets.LABEl_TOKEN}}
        run: |
          curl -X POST  -H "Accept: application/vnd.github+json" \
            -H "Authorization: token $REPO_TOKEN" \
            ${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/assignees \
            -d '{"assignees":["fish9167"]}'
          exit 0
