name: list-pr

on: [push, pull_request]

jobs:
  list-pr:
    runs-on: ubuntu-latest
    steps:
      - name: listPullRequests
        uses: buildsville/list-pull-requests@v1
        id: list
        with:
          token: ${{secrets.ACCESS_TOKEN}}
          labels: '["contribution"]'
          skip_hour: '0'
      - name: output
        run: echo ${{ steps.list.outputs.pulls }}
        
      - name: Comment on PR
        uses: tiwanari/list-merged-pull-requests@master
        with:
          token: ${{ secrets.ACCESS_TOKEN }}        
