name: organization

on: push

jobs:
  organization-member:
    runs-on: ubuntu-latest
    steps:
      - name: run curl
        run: |
          echo `curl -I -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/OperationsYU/members`
          echo `curl -I -H "Authorization: ${{ secrets.ACCESS_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/OperationsYU/members`
        
          
      - name: Check organization
        id: is_organization_member
        uses: actions/github-script@v5
        with:
          #github-token: ${{ secrets.ACCESS_TOKEN }}
          script: |
            const response = await github.rest.orgs.checkMembershipForUser({
              org: 'OperationsYU',
              usernmae: 'fish0607'
            })
            console.log(response)
            #return "Hello!"
            #result-encoding: string

      - name: echo result
        run:
          echo "${{steps.is_organization_member.outputs.result}}" 

