name: organization

on: push

jobs:
  organization-member:
    runs-on: ubuntu-latest
    steps:
      - name: run curl
        run: |
          echo `curl  -I -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/OperationsYU/members/fish0607`
          echo "======"
          echo `curl -I -H "Authorization: ${{ secrets.ACCESS_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/OperationsYU/members/fish0607`
          echo "======"
          echo `curl  -I -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/OperationsYU/members/fish9167`
          echo "======"
          echo `curl -I -H "Authorization: ${{ secrets.ACCESS_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/OperationsYU/members/fish9167`
          
      - name: Check organization
        id: is_organization_member
        uses: OperationsYU/is-organization-member@master
        with:
          organization: OperationsYU
          username: ${{ github.event.pull_request.user.login }}
          token: ${{ secrets.ACCESS_TOKEN }}

