name: organization

on: push

jobs:
  organization-member:
    runs-on: ubuntu-latest
    steps:
      - name: Check organization
        id: is_organization_member
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const response = await github.rest.rest.orgs.checkMembershipForUser({
              org: OperationsYU,
              username: fish0607
            })
            return "Hello!"
            result-encoding: string

      - name: echo result
        run:
          echo "${{steps.is_organization_member.outputs.result}}" 

