name: organization

on: push

jobs:
  organization-member:
    runs-on: ubuntu-latest
    steps:
      - name: run curl
        id: get_check_code
        run: |
          http_code=`curl -s --head -I -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/OperationsYU/members/fish0607 | awk '/HTTP/{print $2}'`
          echo "${http_code}"
          echo "======"
          http_code=`curl -s --head -I -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/OperationsYU/members/fish9167 | awk '/HTTP/{print $2}'`
          echo "${http_code}"
          echo "======"          
          
      - name: Check organization
        id: is_organization_member
        uses: OperationsYU/is-organization-member@master
        with:
          organization: OperationsYU
          #username: ${{ github.event.pull_request.user.login }}
          username: fish0607
          token: ${{ secrets.ACCESS_TOKEN }}

