name: organization

on: push

jobs:
  automate-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check organization
        id: is_organization_member
        uses: OperationsYU/is-organization-member@master
        with:
          organization: OperationsYU
          username: fish9167
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Echo username organization
        run: |
          echo ${{ github.event.push.user.login }}
          echo ${{ steps.is_organization_member.outputs.result }}

      - name: Check organization
        id: is_organization_member2
        uses: OperationsYU/is-organization-member@master
        with:
          organization: OperationsYU
          username: fish0607
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Echo username organization
        run: |
          echo ${{ github.event.push.user.login }}
          echo ${{ steps.is_organization_member2.outputs.result }}
          
