name: organization

on: push

jobs:
  organization-member:
    runs-on: ubuntu-latest
    steps:
      - name: Check organization
        id: is_organization_member
        run: |
         org="OperationsYU"
         username="fish0607"
         result=`curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/${org}/members/${username}`
         echo ${username} ${result}
         username2="fish9167"
         result=`curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/${org}/members/${username2}`
         echo ${username2} ${result}
         
