name: read_body

on: 
  issue_comment:
    types: [created, edited]
  pull_request_review_comment:
    types: [created, edited]
    
jobs:
  read_body:
    if: |
      contains(github.event.comment.body, '- [x] wahah')
    runs-on: ubuntu-latest

    steps:
      - name: echo 
        run:
          echo ${{ github.event.comment.body }}
