name: run test cases

on: 
  issue_comment:
    types: [created, edited]
  pull_request_review_comment:
    types: [created, edited]
    
jobs:
  read_body:
    runs-on: ubuntu-latest

    steps:
      - name: echo 
        run:
          echo ${{ github.event.comment.body }}
