name: read_body

on:
  pull_request:
  issue_comment:
    types: [created, edited]
  pull_request_review_comment:
    types: [created, edited]
    
jobs:
  read_body:
    if: |
      contains(github.event.comment.body, '- [x] wahah') &&
      ! contains(github.event.pull_request.title, '[skip ci]')
    runs-on: ubuntu-latest

    steps:
      - name: echo 
        run:
          echo ${{ github.event.comment.body }}
