name: run test cases

on: 
  pull_request_target:
  issue_comment:
    types: [created, edited]

# github.head_ref is only defined on pull_request events
concurrency:
  group: ${{ github.workflow }}-${{ github.actor }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  macOS-RunTestCases:
    if: |
      contains(github.event.pull_request.body, '[X] needs automatic test cases check') ||
      contains(github.event.comment.body, '@cocos-robot run test cases')
    runs-on: self-hosted-mac

    steps:
      - name: Checkout test-projects
        uses: actions/checkout@v3
        with:
          repository: cocos/cocos-test-projects
          fetch-depth: 0
          ref: v3.7
          path: ../../cocos-test-projects
  

# Creator-PR-RunTestCases:
#     runs-on: self-hosted-mac
#     needs: [macOS-RunTestCases, Win-RunTestCases]
#     steps:
#       - name: Run test cases
#         timeout-minutes: 90
#         id: run_test_cases
#         run: |
#           cd ..
#           python3 -u ./python/main.py --workspace ${{github.workspace}} --pr_number ${{ steps.get_pr.outputs.pr_number }} --author ${{ steps.parse_pr.outputs.pr_author }}  --base_ref ${{ steps.parse_pr.outputs.pr_base_ref }}  --base_sha  ${{ steps.parse_pr.outputs.pr_base_sha }}  --head_ref  ${{ steps.parse_pr.outputs.pr_head_ref }} --head_sha ${{ steps.parse_pr.outputs.pr_head_sha }}


#       - name: Checkout
#         uses: actions/checkout@v3
#         with:
#           repository: cocos-robot/cocos-editor
#           ref: ${{ steps.get_branch.outputs.submit_branch }}
#           fetch-depth: 0
#           token: ${{ secrets.PR_TOKEN }}


#       - name: Update Comment
#         uses: peter-evans/create-or-update-comment@v1
#         with:
#           issue-number: ${{ steps.get_pr.outputs.pr_number }}
#           body: |
#             @${{ steps.parse_pr.outputs.pr_author }}, Please check the result of `run test cases`:
#             - Test Platform: macOS
#             - Editor Version: ${{ steps.run_test_cases.outputs.editor }}
#             - Task Result: ${{ steps.run_test_cases.outputs.task }}
#             - Task URL: ${{ steps.run_test_cases.outputs.url }}
#             - GitHub Action: https://github.com/cocos/cocos-engine/actions/runs/${{ github.run_id }}
#             ## Task Details
#             ${{ steps.run_test_cases.outputs.report }}


























