name: slefhost

on: 
  - pull_request
  - pull_request_target


jobs:
  slefhost:
    runs-on: run-test-win01
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'output'
        id: task
        run: python output.py

      - name: 'get output'
        run: echo ${{ steps.task.outputs.msg }}
