name: windows

on: [push, pull_request]

jobs:
  self-hosted:
    #runs-on: windows-2016
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: echo
      run: |
        echo %PATH%  
